### PR TITLE
feat(filter-field): Custom parser example

### LINKED ISSUE #1508: DtExampleFilterFieldCustomParser missing in barista-examples
# Bug Report

DtExampleFilterFieldCustomParser missing in barista-examples.

## Steps to Reproduce

- https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldCustomParser/

## Attachments

open-in-stackblitz
DTExampleFilterFieldCustomParser-missing

### PR DESCRIPTION
**Pull request by TannerGilbert**
Added custom parser example that was missing as mentioned in  dynatrace-oss/barista#1508.

Closes dynatrace-oss/barista#1508

### CODE REVIEW

**Comment by lukasholzer** [comment]
Hey @TannerGilbert thank you very much for tackling this issue. One question in advance has anybody guided you for this or told you how to accomplish that?

Because we have custom schematics for generating those examples. @bardosmisi did a great job on implementing them.
So maybe he can give you a short rampup on how to create those examples :)

**Comment by TannerGilbert** [comment]
@lukasholzer no I didn't have any guidance for this. It just seemed straight forward so I implemented it. I also didn't know that you have some kind of schematics for creating those examples but I'd be interested in learning about them and changing my code if needed.

**Comment by lukasholzer** [comment]
Yea this repository consists out of generated code so adding a PR there won't help very much as it will be removed with the next update. So The examples are generated out of the barista examples in the barista repo where you can add one with the schematics and then they are getting generated and pushed in this repo for stackblitz.

In the barista repository is a npm task that can be executed: `npm run shareable-examples` that will build this output.

So I will close this PR here.

**Comment by TannerGilbert** [comment]
@lukasholzer the example already exists in [barista/libs/examples/src/filter-field/filter-field-custom-parser-example/](https://github.com/dynatrace-oss/barista/tree/48213d6e378caf9b9a22f02bda4e43f183c25a48/libs/examples/src/filter-field/filter-field-custom-parser-example). So I think the only reason why it is missing here is because your Jenkins pipeline wasn't executed after the example was added.

**Pull request closed without merging**
